-- ==========================================
-- 10xWorkforce.AI Master Data & Seed Query
-- ==========================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS projects_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code TEXT UNIQUE,
    project_name TEXT,
    client_name TEXT,
    total_budget NUMERIC,
    created_at DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS master_camps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camp_code TEXT UNIQUE,
    camp_name TEXT,
    location TEXT,
    total_bed_capacity NUMERIC,
    current_occupied_beds NUMERIC DEFAULT 0,
    camp_manager_name TEXT
);

CREATE TABLE IF NOT EXISTS sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name TEXT UNIQUE,
    site_code TEXT,
    location TEXT,
    total_budget NUMERIC DEFAULT 0,
    required_manpower NUMERIC DEFAULT 0,
    parent_project_code TEXT,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS master_employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT UNIQUE,
    employee_name TEXT,
    trade TEXT,
    labor_type TEXT,
    base_salary NUMERIC,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS master_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code TEXT UNIQUE,
    material_name TEXT,
    category TEXT,
    standard_price NUMERIC,
    approved_vendor TEXT
);

CREATE TABLE IF NOT EXISTS master_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name TEXT UNIQUE,
    tool_name TEXT,
    brand TEXT,
    total_owned NUMERIC,
    warranty_expiry DATE
);

-- ==========================================
-- 2. Seed Mock Data
-- ==========================================

-- Seed Projects
INSERT INTO projects_master (project_code, project_name, client_name, total_budget) VALUES
('PRJ-001', 'City Infrastructure Revamp', 'Gov Municipal Dept', 50000000),
('PRJ-002', 'Airport Expansion', 'National Aviation Auth', 120000000),
('PRJ-003', 'Suburban Commercial Zone', 'Retail Group Inc', 35000000)
ON CONFLICT (project_code) DO NOTHING;

-- Seed Camps
INSERT INTO master_camps (camp_code, camp_name, location, total_bed_capacity, current_occupied_beds, camp_manager_name) VALUES
('CMP-001', 'North Zone Labor Camp', 'North Industrial Area', 500, 450, 'Rajiv Kumar'),
('CMP-002', 'South Zone Labor Camp', 'South Industrial Area', 300, 120, 'Ahmed Al-Farsi'),
('CMP-003', 'City Center Premium Camp', 'Downtown Outskirts', 150, 145, 'John Smith')
ON CONFLICT (camp_code) DO NOTHING;

-- Seed Sites
INSERT INTO sites (site_name, site_code, location, total_budget, required_manpower, parent_project_code) VALUES
('Downtown Skyscraper', 'S-001', 'City Center', 5000000, 150, 'PRJ-001'),
('Airport Terminal 3', 'S-002', 'North Zone', 12000000, 300, 'PRJ-002'),
('Riverside Mall', 'S-003', 'East District', 8000000, 200, 'PRJ-003'),
('Suburban Housing Complex', 'S-004', 'West End', 3500000, 80, 'PRJ-001'),
('Metro Station Alpha', 'S-005', 'South Zone', 9000000, 120, 'PRJ-001')
ON CONFLICT (site_name) DO NOTHING;

-- Seed Employees
INSERT INTO master_employees (employee_id, employee_name, trade, labor_type, base_salary) VALUES
('EMP-101', 'John Doe', 'Electrician', 'Direct', 3500),
('EMP-102', 'Ali Khan', 'Mason', 'Subcontractor', 2800),
('EMP-103', 'Carlos Ray', 'Plumber', 'Direct', 3200),
('EMP-104', 'Raj Patel', 'Foreman', 'Direct', 5500),
('EMP-105', 'Mike Smith', 'Welder', 'Direct', 3800),
('EMP-106', 'David Lee', 'Carpenter', 'Subcontractor', 3000),
('EMP-107', 'Sarah Connor', 'Engineer', 'Direct', 8500),
('EMP-108', 'James Bond', 'Security', 'Direct', 2500),
('EMP-109', 'Tony Stark', 'Technician', 'Direct', 4200),
('EMP-110', 'Bruce Wayne', 'Site Manager', 'Direct', 12000)
ON CONFLICT (employee_id) DO NOTHING;

-- Seed Materials
INSERT INTO master_materials (material_code, material_name, category, standard_price, approved_vendor) VALUES
('MAT-001', 'Portland Cement (50kg)', 'Raw Material', 8.50, 'BuildCorp Supplies'),
('MAT-002', 'Steel Rebar (12mm)', 'Raw Material', 45.00, 'IronWorks Inc'),
('MAT-003', 'Copper Wiring (100m)', 'Electrical', 120.00, 'VoltTech Distributors'),
('MAT-004', 'PVC Pipe (4 inch)', 'Plumbing', 15.75, 'AquaFlow Solutions'),
('MAT-005', 'Safety Helmet', 'PPE', 12.00, 'SafeGear Pro'),
('MAT-006', 'High-Vis Vest', 'PPE', 8.50, 'SafeGear Pro'),
('MAT-007', 'LED Floodlight', 'Electrical', 65.00, 'VoltTech Distributors'),
('MAT-008', 'Concrete Blocks', 'Raw Material', 2.50, 'BuildCorp Supplies'),
('MAT-009', 'Gypsum Board', 'Finishing', 18.00, 'Interior Decor Ltd'),
('MAT-010', 'Industrial Paint (20L)', 'Finishing', 85.00, 'ColorChem Industries')
ON CONFLICT (material_code) DO NOTHING;

-- Seed Tools
INSERT INTO master_tools (tag_name, tool_name, brand, total_owned, warranty_expiry) VALUES
('TOOL-DR-01', 'Impact Drill', 'DeWalt', 15, '2027-12-31'),
('TOOL-DR-02', 'Rotary Hammer', 'Bosch', 10, '2026-06-30'),
('TOOL-SA-01', 'Circular Saw', 'Makita', 8, '2026-10-15'),
('TOOL-GR-01', 'Angle Grinder', 'Milwaukee', 20, '2025-08-20'),
('TOOL-ME-01', 'Laser Measure', 'Leica', 5, '2028-01-01'),
('TOOL-WE-01', 'Welding Machine', 'Lincoln Electric', 4, '2027-03-10'),
('TOOL-CO-01', 'Air Compressor', 'Ingersoll Rand', 3, '2029-05-15'),
('TOOL-JA-01', 'Jackhammer', 'Hilti', 6, '2026-11-30'),
('TOOL-PU-01', 'Water Pump', 'Honda', 5, '2025-12-31'),
('TOOL-GE-01', 'Portable Generator', 'Yamaha', 4, '2028-07-01')
ON CONFLICT (tag_name) DO NOTHING;
