-- 10xWorkforce.AI Master Data & Module Tables (All Time/Date standardized)

-- ==========================================
-- MASTER DATA TABLES (Required for AI Agents)
-- ==========================================

-- M1. Sites (Projects) Master
CREATE TABLE IF NOT EXISTS sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name TEXT UNIQUE,
    site_code TEXT,
    location TEXT,
    total_budget NUMERIC DEFAULT 0,
    required_manpower NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Active'
);

-- M2. Employees Master
CREATE TABLE IF NOT EXISTS master_employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT UNIQUE,
    employee_name TEXT,
    trade TEXT,
    labor_type TEXT,
    base_salary NUMERIC,
    status TEXT DEFAULT 'Active'
);

-- M3. Materials Master
CREATE TABLE IF NOT EXISTS master_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code TEXT UNIQUE,
    material_name TEXT,
    category TEXT,
    standard_price NUMERIC,
    approved_vendor TEXT
);

-- M4. Tools Master
CREATE TABLE IF NOT EXISTS master_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name TEXT UNIQUE,
    tool_name TEXT,
    brand TEXT,
    total_owned NUMERIC,
    warranty_expiry DATE
);

-- ==========================================
-- TRANSACTION / MODULE TABLES
-- ==========================================

-- 1. Daily Manpower
CREATE TABLE IF NOT EXISTS daily_manpower (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "logType" TEXT,
    "siteNo" TEXT,
    "siteName" TEXT,
    location TEXT,
    "startTime" TIME,
    "endTime" TIME,
    engineer TEXT,
    foreman TEXT,
    driver TEXT,
    "otherStaff" TEXT,
    "otherStaffTrade" TEXT,
    "taskTitle" TEXT,
    remarks TEXT,
    date DATE DEFAULT CURRENT_DATE,
    "agent_status" TEXT DEFAULT 'pending',
    "agent_metadata" JSONB
);

-- 2. Camp Boss
CREATE TABLE IF NOT EXISTS camp_boss (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employeeId" TEXT,
    "employeeName" TEXT,
    "campLocation" TEXT,
    "roomNumber" TEXT,
    status TEXT,
    remarks TEXT,
    date DATE DEFAULT CURRENT_DATE,
    "agent_status" TEXT DEFAULT 'pending',
    "agent_metadata" JSONB
);

-- 3. Petty Cash
CREATE TABLE IF NOT EXISTS petty_cash (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pettyCashHolder" TEXT,
    "supplierName" TEXT,
    description TEXT,
    "projectCode" TEXT,
    "projectName" TEXT,
    currency TEXT,
    amount NUMERIC,
    vat NUMERIC,
    "totalAmount" NUMERIC,
    "invoiceUrisJson" JSONB,
    date DATE DEFAULT CURRENT_DATE,
    "agent_status" TEXT DEFAULT 'pending',
    "agent_metadata" JSONB
);

-- 4. MR Procurement
CREATE TABLE IF NOT EXISTS mr_procurement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mrNo" TEXT,
    "employeeId" TEXT,
    "requestedBy" TEXT,
    "projectCode" TEXT,
    "projectName" TEXT,
    "siteCode" TEXT,
    "siteName" TEXT,
    "supplierName" TEXT,
    "materialName" TEXT,
    remarks TEXT,
    quantity NUMERIC,
    "unitPrice" NUMERIC,
    "requestedDate" DATE,
    "requiredDate" DATE,
    "agent_status" TEXT DEFAULT 'pending',
    "agent_metadata" JSONB
);

-- 5. Employee Onboarding
CREATE TABLE IF NOT EXISTS employee_onboarding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employeeName" TEXT,
    dob DATE,
    nationality TEXT,
    "countryCode" TEXT,
    "mobileNo" TEXT,
    trade TEXT,
    "dateOfJoining" DATE,
    "laborType" TEXT,
    accommodation TEXT,
    "passportNo" TEXT,
    "passportExpiry" DATE,
    "visaStatus" TEXT,
    "visaExpiry" DATE,
    "passportInLocker" BOOLEAN DEFAULT false,
    "passportScanUrisJson" JSONB,
    "employeePhotoUrisJson" JSONB,
    "certificatesJson" JSONB,
    "drivingLicenseUrisJson" JSONB,
    "consentFormUrisJson" JSONB,
    "employeeStatus" TEXT,
    "onboardingStatus" TEXT,
    remarks TEXT,
    "agent_status" TEXT DEFAULT 'pending',
    "agent_metadata" JSONB
);

-- 6. Tools Management (Checkout / Return)
CREATE TABLE IF NOT EXISTS tools_management (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "itemName" TEXT,
    brand TEXT,
    "tagName" TEXT,
    "warrantyDetails" TEXT,
    "purchaseDate" DATE,
    quantity NUMERIC,
    "assignedTo" TEXT,
    "checkoutPhotoUrisJson" JSONB,
    "returnedQty" NUMERIC,
    condition TEXT,
    "returnPhotoUrisJson" JSONB,
    "checkoutDate" DATE DEFAULT CURRENT_DATE,
    "returnDate" DATE,
    "agent_status" TEXT DEFAULT 'pending',
    "agent_metadata" JSONB
);

-- 7. Work Output
CREATE TABLE IF NOT EXISTS work_output (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "projectCode" TEXT,
    "projectName" TEXT,
    "technicianId" TEXT,
    "technicianName" TEXT,
    trade TEXT,
    "foremanId" TEXT,
    "foremanName" TEXT,
    "workDescription" TEXT,
    "unitOfMeasure" TEXT,
    "outputPerDay" NUMERIC,
    date DATE DEFAULT CURRENT_DATE,
    "agent_status" TEXT DEFAULT 'pending',
    "agent_metadata" JSONB
);

-- 8. Supervisor Reports (Orchestrator Output)
CREATE TABLE IF NOT EXISTS supervisor_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_status TEXT,
    key_bottleneck TEXT,
    orchestrated_action_plan TEXT,
    financial_impact_risk TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
